version: "3"
services:
  mongo:
    container_name: crossflow-mongo
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    networks:
      - crossflow 
networks:
  crossflow:
    driver: bridge
